### ISSUE TITLE
cannot build rocFFT on CUDA

### ISSUE THREAD

**Issue by tingxingdong** [ROCmSoftwarePlatform/rocFFT#385]
### What is the expected behavior
-  Build Pass

### What actually happens
-  Build Fail
- multiple defenition in files rtc_compile.cpp and rocfft_rtc_helper.cpp
- 
timdong@ubuntu-Precision-3630-Tower:~/rocFFT/build$ make VERBOSE=1
/snap/cmake/1186/bin/cmake -S/home/timdong/rocFFT -B/home/timdong/rocFFT/build --check-build-system CMakeFiles/Makefile.cmake 0
/snap/cmake/1186/bin/cmake -E cmake_progress_start /home/timdong/rocFFT/build/CMakeFiles /home/timdong/rocFFT/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/timdong/rocFFT/build'
make  -f library/src/CMakeFiles/rocfft_rtc_helper.dir/build.make library/src/CMakeFiles/rocfft_rtc_helper.dir/depend
make[2]: Entering directory '/home/timdong/rocFFT/build'
cd /home/timdong/rocFFT/build && /snap/cmake/1186/bin/cmake -E cmake_depends "Unix Makefiles" /home/timdong/rocFFT /home/timdong/rocFFT/library/src /home/timdong/rocFFT/build /home/timdong/rocFFT/build/library/src /home/timdong/rocFFT/build/library/src/CMakeFiles/rocfft_rtc_helper.dir/DependInfo.cmake --color=
Dependencies file "library/src/CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o.d" is newer than depends file "/home/timdong/rocFFT/build/library/src/CMakeFiles/rocfft_rtc_helper.dir/compiler_depend.internal".
Dependencies file "library/src/CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o.d" is newer than depends file "/home/timdong/rocFFT/build/library/src/CMakeFiles/rocfft_rtc_helper.dir/compiler_depend.internal".
Consolidate compiler generated dependencies of target rocfft_rtc_helper
make[2]: Leaving directory '/home/timdong/rocFFT/build'
make  -f library/src/CMakeFiles/rocfft_rtc_helper.dir/build.make library/src/CMakeFiles/rocfft_rtc_helper.dir/build
make[2]: Entering directory '/home/timdong/rocFFT/build'
[  0%] Linking CXX executable rocfft_rtc_helper
cd /home/timdong/rocFFT/build/library/src && /snap/cmake/1186/bin/cmake -E cmake_link_script CMakeFiles/rocfft_rtc_helper.dir/link.txt --verbose=1
/usr/bin/g++ -O3 -DNDEBUG -L/usr/local/cuda/lib64 -pthread CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o -o rocfft_rtc_helper  -lnvrtc -lnvrtc-builtins -lnvptxcompiler_static -lcuda
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcGetErrorString':
rtc_compile.cpp:(.text+0x0): multiple definition of `hiprtcGetErrorString'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x0): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcVersion':
rtc_compile.cpp:(.text+0xd0): multiple definition of `hiprtcVersion'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0xd0): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcAddNameExpression':
rtc_compile.cpp:(.text+0x1a0): multiple definition of `hiprtcAddNameExpression'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x1a0): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcCompileProgram':
rtc_compile.cpp:(.text+0x270): multiple definition of `hiprtcCompileProgram'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x270): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcCreateProgram':
rtc_compile.cpp:(.text+0x340): multiple definition of `hiprtcCreateProgram'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x340): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcDestroyProgram':
rtc_compile.cpp:(.text+0x410): multiple definition of `hiprtcDestroyProgram'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x410): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcGetLoweredName':
rtc_compile.cpp:(.text+0x4e0): multiple definition of `hiprtcGetLoweredName'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x4e0): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcGetProgramLog':
rtc_compile.cpp:(.text+0x5b0): multiple definition of `hiprtcGetProgramLog'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x5b0): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcGetProgramLogSize':
rtc_compile.cpp:(.text+0x680): multiple definition of `hiprtcGetProgramLogSize'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x680): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcGetCode':
rtc_compile.cpp:(.text+0x750): multiple definition of `hiprtcGetCode'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x750): first defined here
CMakeFiles/rocfft_rtc_helper.dir/rtc_compile.cpp.o: In function `hiprtcGetCodeSize':
rtc_compile.cpp:(.text+0x820): multiple definition of `hiprtcGetCodeSize'
CMakeFiles/rocfft_rtc_helper.dir/rocfft_rtc_helper.cpp.o:rocfft_rtc_helper.cpp:(.text+0x820): first defined here
collect2: error: ld returned 1 exit status
library/src/CMakeFiles/rocfft_rtc_helper.dir/build.make:112: recipe for target 'library/src/rocfft_rtc_helper' failed
make[2]: *** [library/src/rocfft_rtc_helper] Error 1
make[2]: Leaving directory '/home/timdong/rocFFT/build'
CMakeFiles/Makefile2:159: recipe for target 'library/src/CMakeFiles/rocfft_rtc_helper.dir/all' failed
make[1]: *** [library/src/CMakeFiles/rocfft_rtc_helper.dir/all] Error 2
make[1]: Leaving directory '/home/timdong/rocFFT/build'
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2

### How to reproduce
install rocm-4.5.2 and hip-nvcc 
cd build 
 cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENTS=OFF -DBUILD_WITH_LIB=CUDA -DUSE_CUDA=ON -DCUDA_PREFIX=/usr/local/cuda -DCUDA_ARCH=sm_7.5
make 

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v4.5.2 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by tingxingdong** [comment]
if building with hipcc(nvcc), it has different error :  nvcc fatal   : Value 'gnu++1z' is not defined for option 'std'
===

[  0%] Building CXX object library/src/CMakeFiles/rocfft-rtc-compile.dir/rtc_compile.cpp.o
cd /home/timdong/rocFFT/hipcc_build/library/src && /opt/rocm/bin/hipcc  -I/home/timdong/rocFFT/library/src/include -I/home/timdong/rocFFT/library/include -I/home/timdong/rocFFT/hipcc_build/_deps/sqlite_local-src -O3 -DNDEBUG -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/opt/rocm-4.5.2/hip/include -I/usr/local/cuda/include -D__HIP_PLATFORM_NVIDIA__ -Wall -Wno-unused-function -Wimplicit-fallthrough -Wunreachable-code -Wsign-compare -DROCFFT_RUNTIME_COMPILE -std=gnu++1z -MD -MT library/src/CMakeFiles/rocfft-rtc-compile.dir/rtc_compile.cpp.o -MF CMakeFiles/rocfft-rtc-compile.dir/rtc_compile.cpp.o.d -o CMakeFiles/rocfft-rtc-compile.dir/rtc_compile.cpp.o -c /home/timdong/rocFFT/library/src/rtc_compile.cpp
nvcc fatal   : Value 'gnu++1z' is not defined for option 'std'
===

**Comment by doctorcolinsmith** [comment]
@tingxingdong Thanks for reporting the error.  We will investigate the build failure.

**Comment by doctorcolinsmith** [comment]
Also, please note that supported method of portability to NVIDIA hardware is to use hipFFT.  Compiling rocFFT directly to CUDA is not officially supported.

**Comment by evetsso** [comment]
Hi @tingxingdong, thanks for the bug report.

The multiple definition problem you mention was fixed in ROCm 5.1 - it is a problem in the hipRTC header files which implement function bodies but does not give them static linkage, so you end up with duplicate symbols in the build.

Once you get past that error, you will hit other problems.  In the past, we have put some effort into making rocFFT build on CUDA but this is not actively maintained.  The build is not expected to work at this time.

Will hipFFT solve your problem, as @doctorcolinsmith suggests?

**Comment by tingxingdong** [comment]
Thanks for the quick reply. I tested ROCm 5.0 and ROCm 4.5.2  later and confirm that the same multiple definition problems exist newer ROCm as well (i.e 5.0 and 4.5.2). 

I can build hipFFT but  hipFFT will switch to cuFFT on CUDA which is not I want.

**Comment by tingxingdong** [comment]
I later tested on ROCm 5.1 and the same multiple defintion problem still exist

**Comment by evetsso** [comment]
@tingxingdong Sorry, it looks like I got the release number wrong - 5.2 should fix this.  nvidia_hiprtc.h has functions like hiprtcGetErrorString which were not static in earlier releases, but 5.2 and later gives them static linkage.

**Comment by evetsso** [comment]
I'm closing this issue, as this specific problem should have been addressed in ROCm 5.2.

As previously mentioned, building rocFFT to use CUDA is not officially supported and only sees occasional maintenance.  It is not expected to work at this point.  We may put some additional effort towards making this work in the future.
